name: CuratedLists
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"
permissions: write-all
jobs:
  build:
    name: Run CuratedLists
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: CuratedLists
        run: |
          .\Curated-Lists-Creation.ps1
        shell: pwsh

